sonar.projectKey=LibreHousehold_Frontend
sonar.organization=nicklas2751-github

# Path is relative to the sonar-project.properties file.
sonar.sources=src

# Exclude generated sources
sonar.exclusions=src/generated-sources/**,src/lib/paraglide/**,node_modules/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8
