sonar.projectKey=LibreHousehold_Backend
sonar.organization=nicklas2751-github

# Pfade relativ zu sonar-project.properties
sonar.sources=src/main
sonar.tests=src/test

# Generierte Quellen ausschließen
sonar.exclusions=target/generated-sources/**

# Java-spezifische Konfiguration
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Kodierung
sonar.sourceEncoding=UTF-8
