spring:
  application:
    name: librehousehold
  modulith:
    runtime:
      flyway-enabled: true
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080

librehousehold:
  auth:
    client-id: librehousehold-spa
    redirect-uri: http://localhost:5173/callback

server:
  tomcat:
    max-http-post-size: -1
