:jbake-title: Cross-cutting Concepts
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 8
:filename: /chapters/08_concepts.adoc
:imagesdir: ../images

:toc:

[[section-concepts]]
== Cross-cutting Concepts

=== Architecture Decision Records (ADRs)

Architecture Decision Records (ADRs) are a way to document important architectural decisions in a structured manner. They help in maintaining a record of the rationale behind decisions, alternatives considered, and the implications of those decisions. For more information see https://adr.github.io[adr.github.io].

=== Modular Monolith (Modulith)

A modular monolith, or "modulith", is an architectural style where the application is structured into distinct modules within a single deployable unit. Each module encapsulates specific functionality and can interact with other modules through well-defined interfaces. This approach combines the benefits of modularity with the simplicity of a monolithic deployment. For more information see the https://spring.io/blog/2022/10/21/introducing-spring-modulith[Spring Modulith blog post] or https://entwickler.de/software-architektur/microservices-oder-monolithen-beides[this german Entwickler.de article about moduliths].